num_classes: 3
lr: 0.001
batch_size: 2
epochs: 5
num_workers: 2
image_height: 448
image_width: 448
pin_memory: True
load_model: False
model_load_path: "model/model_5.pth"

scheduler: "lambda"
scheduler_alpha: 0.99

activation: "gelu"

train_image_dir: "data/images"
train_mask_dir: "data/annotations/trimaps"
mask_bg: 1 # 2 - 1

save_dir: "output"
save_every: 5
model_save_name: "model.pth"
# wandb: True
# wandb_project: "unet-oxford-iiit-pet-dataset"
