num_classes: 3
lr: 0.001
batch_size: 8
epochs: 5
num_workers: 2
image_height: 160
image_width: 240
pin_memory: True
load_model: False
save_every: 1

activation: "gelu"

train_image_dir: "data/images"
train_mask_dir: "data/annotations/trimaps"
mask_bg: 1 # 2 - 1

model_load_path: "model/model_5.pth"
model_save_path: "model/model.pth"
